#通用配置，指定环境
spring:
  #指定环境
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
#测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082

---
#生产环境
spring:
  config:
    activate:
      on-profile: port
server:
  port: 8083
